apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone-container
        # Replace with your actual image and latest tag from Build #6
        image: sushantnm/capstone-app:latest
        ports:
        - containerPort: 80
